// 50 Quiz Questions about Cécifoot
export const quizQuestions = [
    { q: "Combien de joueurs de champ composent une équipe de cécifoot B1 ?", a: ["4", "5", "6", "7"], correct: 0 },
    { q: "Quel mot les joueurs crient-ils pour signaler leur approche du ballon ?", a: ["VOY", "ICI", "BALL", "STOP"], correct: 0 },
    { q: "En quelle année le cécifoot est-il devenu sport paralympique ?", a: ["2000", "2004", "2008", "1996"], correct: 1 },
    { q: "Quelle est la dimension du terrain de cécifoot B1 ?", a: ["42x22m", "50x30m", "30x20m", "60x40m"], correct: 0 },
    { q: "Le gardien de but en cécifoot B1 est-il voyant ou non-voyant ?", a: ["Voyant", "Non-voyant", "Malvoyant", "Peu importe"], correct: 0 },
    { q: "Comment les joueurs repèrent-ils le ballon ?", a: ["Par les grelots qu'il contient", "Par un signal sonore externe", "Par vibration", "Par la voix de l'arbitre"], correct: 0 },
    { q: "Quelle est la durée d'une mi-temps en championnat de France B1 ?", a: ["20 minutes", "25 minutes", "15 minutes", "30 minutes"], correct: 0 },
    { q: "Que signifie la catégorie B1 ?", a: ["Non-voyants", "Malvoyants", "Voyants", "Handicap moteur"], correct: 0 },
    { q: "Dans quel pays le cécifoot a-t-il été formalisé dans les années 1960 ?", a: ["Brésil", "France", "Espagne", "Argentine"], correct: 0 },
    { q: "Quel est le surnom de l'équipe nationale argentine de cécifoot ?", a: ["Los Murciélagos", "Los Tigres", "Los Leones", "Los Águilas"], correct: 0 },
    { q: "Quelle fédération française est délégataire pour le cécifoot ?", a: ["Fédération Française Handisport", "FFF", "FFSA", "UNSS"], correct: 0 },
    { q: "Que portent les joueurs B1 sur les yeux ?", a: ["Un bandeau", "Des lunettes noires", "Rien", "Un masque"], correct: 0 },
    { q: "Où se trouve le guide qui aide les attaquants ?", a: ["Derrière le but adverse", "Sur le côté", "Au milieu du terrain", "Dans les tribunes"], correct: 0 },
    { q: "Y a-t-il une règle de hors-jeu en cécifoot ?", a: ["Non", "Oui", "Seulement en B2", "Seulement en finale"], correct: 0 },
    { q: "Quelle est la hauteur des barrières latérales ?", a: ["1,30 mètre", "1 mètre", "2 mètres", "0,5 mètre"], correct: 0 },
    { q: "En quelle année le premier club français de cécifoot a-t-il été créé ?", a: ["1987", "1990", "1980", "1995"], correct: 0 },
    { q: "Quel est le nom du premier club français de cécifoot ?", a: ["AS Cécifoot Saint-Mandé", "PSG Cécifoot", "OL Cécifoot", "OM Cécifoot"], correct: 0 },
    { q: "Combien d'équipes de cécifoot existe-t-il en France environ ?", a: ["9", "5", "15", "20"], correct: 0 },
    { q: "Que signifie 'J'ai' en cécifoot ?", a: ["Le joueur a le ballon", "Le joueur veut le ballon", "Le joueur est fatigué", "Le joueur sort"], correct: 0 },
    { q: "Que signifie 'Oui' en cécifoot ?", a: ["On peut passer le ballon", "Le joueur refuse", "Demande de temps mort", "Appel à l'arbitre"], correct: 0 },
    { q: "Où s'est déroulé le premier championnat mondial de cécifoot ?", a: ["Brésil", "France", "Espagne", "Japon"], correct: 0 },
    { q: "En quelle année a eu lieu le premier championnat mondial ?", a: ["1997", "2000", "1990", "2004"], correct: 0 },
    { q: "Quelle organisation internationale régit le cécifoot ?", a: ["IBSA", "FIFA", "CIO", "UEFA"], correct: 0 },
    { q: "Que signifie IBSA ?", a: ["International Blind Sports Federation", "International Ball Sports Association", "International Blind Soccer Association", "International Board Sports Authority"], correct: 0 },
    { q: "Combien de remplaçants peut avoir une équipe B1 ?", a: ["4", "3", "5", "2"], correct: 0 },
    { q: "À partir de quel âge peut-on jouer au cécifoot en compétition ?", a: ["15 ans", "12 ans", "18 ans", "10 ans"], correct: 0 },
    { q: "Quelle est la durée d'une mi-temps en compétition européenne ?", a: ["25 minutes", "20 minutes", "30 minutes", "15 minutes"], correct: 0 },
    { q: "Existe-t-il une compétition féminine de cécifoot aux Jeux Paralympiques ?", a: ["Non", "Oui", "Depuis 2020", "En projet"], correct: 0 },
    { q: "Quelle catégorie est admise aux Jeux Paralympiques ?", a: ["B1 uniquement", "B2-B3", "Toutes", "Aucune"], correct: 0 },
    { q: "Quel type de surface est utilisé pour le terrain ?", a: ["Gazon synthétique", "Terre battue", "Béton", "Sable"], correct: 0 },
    { q: "À quelle distance se tire la double pénalité ?", a: ["8 mètres", "6 mètres", "11 mètres", "5 mètres"], correct: 0 },
    { q: "À partir de combien de fautes d'équipe y a-t-il double pénalité ?", a: ["5 fautes", "3 fautes", "7 fautes", "10 fautes"], correct: 0 },
    { q: "Le gardien peut-il sortir de sa surface ?", a: ["Non, limité à 1m devant le but", "Oui, librement", "Jusqu'à 5m", "Seulement sur corner"], correct: 0 },
    { q: "Quel sport a inspiré les barrières latérales du cécifoot ?", a: ["Hockey sur glace", "Tennis", "Basketball", "Handball"], correct: 0 },
    { q: "Où se sont déroulés les premiers Jeux Paralympiques africains incluant le cécifoot ?", a: ["Rabat, Maroc", "Le Caire, Égypte", "Lagos, Nigeria", "Johannesburg, Afrique du Sud"], correct: 0 },
    { q: "En quelle année ont eu lieu les premiers Jeux Paralympiques africains ?", a: ["2020", "2016", "2018", "2022"], correct: 0 },
    { q: "Quel pays a pratiqué le cécifoot dès les années 1920 ?", a: ["Espagne", "Brésil", "France", "Angleterre"], correct: 0 },
    { q: "Quelle marque a créé des bouteilles en braille pour l'équipe argentine ?", a: ["Coca-Cola", "Pepsi", "Fanta", "Sprite"], correct: 0 },
    { q: "Combien de divisions existe-t-il en catégorie B2-B3 en France ?", a: ["2", "1", "3", "4"], correct: 0 },
    { q: "Combien de joueurs B2 minimum doivent être sur le terrain en B2-B3 ?", a: ["2", "1", "3", "4"], correct: 0 },
    { q: "Les joueurs B2-B3 portent-ils un bandeau ?", a: ["Non", "Oui", "Seulement les B3", "Seulement les B2"], correct: 0 },
    { q: "Quel est le rôle du préposé au guidage ?", a: ["Indiquer la position du but à l'attaquant", "Arbitrer", "Soigner les joueurs", "Gérer les remplacements"], correct: 0 },
    { q: "Pourquoi les spectateurs doivent-ils garder le silence ?", a: ["Pour que les joueurs entendent le ballon", "Par respect", "Règle FIFA", "Pour la télévision"], correct: 0 },
    { q: "Quel type de tir est le plus efficace en cécifoot ?", a: ["Tir soudain sous la barre ou à ras de terre", "Tir en cloche", "Tir à mi-hauteur", "Tir de la tête"], correct: 0 },
    { q: "Qui peut arrêter le match en cas de blessure grave ?", a: ["L'arbitre principal", "Le gardien", "Le guide", "Le coach"], correct: 0 },
    { q: "Quelle protection portent les joueurs autour de la tête ?", a: ["Des protections de sécurité", "Un casque de rugby", "Rien", "Un bandana"], correct: 0 },
    { q: "Quel est le premier pays à avoir organisé un tournoi national de cécifoot ?", a: ["Brésil en 1974", "France en 1987", "Espagne en 1980", "Argentine en 1990"], correct: 0 },
    { q: "Où s'est déroulé le premier championnat européen IBSA ?", a: ["Barcelone", "Paris", "Londres", "Berlin"], correct: 0 },
    { q: "Quelle est la taille du but en cécifoot ?", a: ["Taille d'un but de hockey sur gazon", "Taille d'un but de football", "Taille d'un but de handball", "Taille d'un but de futsal"], correct: 0 },
    { q: "Comment le temps est-il calculé en cécifoot ?", a: ["Chronomètre arrêté à chaque arrêt de jeu", "Temps continu", "Temps additionnel à la fin", "Quarts de 10 minutes"], correct: 0 }
];
